In [0]:
ls

sample_data/


In [0]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [0]:
ls

drive/  sample_data/


In [0]:
cd drive/My\ Drive

/content/drive/My Drive


In [0]:
ls

'Business Model Canvas.gdoc'  'Leftovers .gdoc'
 CITREP_Data+Code/            'Oral Presentation.gdoc'
 Classroom/                   'Quality Control.gdoc'
'Colab Notebooks'/            'Quality Control Slides.gslides'
'Getting started.pdf'


In [0]:
cd CITREP_Data+Code/

/content/drive/My Drive/CITREP_Data+Code


In [0]:
ls

 2a-TensorFlow-Data-Loading.ipynb
 2b-TensorFlow-ML.ipynb
 3a-TF-FcNN-MNIST.ipynb
 3b-TF-FcNN-MNIST-Exercise.ipynb
 3c-FcNN-CIFAR10.ipynb
 3d-FcNN-CIFAR10-Exercise.ipynb
 3-diabetic-NeuralNet-Exercise-TF.ipynb
 3e-keras-FCNN-MNIST.ipynb
 3f-keras-FcNN-dogscats.ipynb
 3g-keras-FcNN-bloodcell-Exercise.ipynb
 3h-keras-FC-AutoEncoder.ipynb
 4a-MNIST-CNN-TF.ipynb
 4b-CIFAR10-CNN-TF-Exercise.ipynb
 5a-keras-CNN-dogscats.ipynb
 5b-keras-CNN-Bloodcell.ipynb
 5c-keras-Con-AutoEncoder.ipynb
 5d-keras-Vgg16-dogscats.ipynb
 5e-Resnet50-keras-dogscats-Exercise.ipynb
 6-Semeion-Classification-SimpleCNN-Exercise.ipynb
 7-RNN-IMDB.ipynb
'CITREP+ - Clarence & Dr Sudipta - Deep Learning with Tensorflow and Python - v2.pdf'
 Data/
 tensorboard.ipynb


In [0]:
import tensorflow as tf
print(tf.__version__)

1.14.0


In [0]:
a=1
b=2
c= a+b
print(a,b,c)

1 2 3


In [0]:
#meanwhile in tensorflow:
a = tf.constant(1)
b = tf.constant(2)
c = tf.add(a,b)
print(a)
print(b)
print(c)

Tensor("Const_2:0", shape=(), dtype=int32)
Tensor("Const_3:0", shape=(), dtype=int32)
Tensor("Add_1:0", shape=(), dtype=int32)


In [0]:
#Within tensorflow you have to run a session, if not you won't be able to run 
#run session:
#just run this once
sess = tf.Session()


In [0]:
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))

#within tensorflow, you won't be able to run different data types

1
2
3


In [0]:
#or
with tf.Session() as sess:
  print(sess.run(a))

1


In [0]:
sess = tf.Session()

a = tf.constant(1, dtype=tf.float32)
b = tf.constant(2.5)
c = tf.add(a,b)
d = tf.floordiv(a,b)

In [0]:
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))
print(sess.run(d))

1.0
2.5
3.5
0.0


In [0]:
#exercise
sess = tf.Session()

a = tf.constant(3, dtype = tf.float32)
b = tf.constant(4.1, dtype = tf.float32)
c = tf.constant(5, dtype = tf.float32)

d = tf.add(tf.multiply(a,b), c) 
print(sess.run(d))

17.3


In [0]:
#building a matrix:
#make sure to put two brackets
a = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
print(sess.run(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
print(sess.run(tf.shape(a)))

[3 3]


In [0]:
#to slice the data 
# [0, 1] is index of [row, column]
#[2, 2] is the dimensions that you want the data to be cut
print(sess.run(tf.slice(a, [0, 1], [2, 2])))

[[2 3]
 [5 6]]


In [0]:
#matrix operators:
a = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
# Transpose - tf.transpose(a) 
# Inverse - tf.matrix_inverse(a) 
# Dot Product – tf.tensordot(a,b, axes=0) 
# Matrix Multiplication - tf.matmul(a, b) 
# Solve A.x = b - tf.matrix_solve(A,b)

In [0]:
#exercise matrix
x = [[1.1,1.2]] w = [[1,2],[3,4]] b = [[2.3,2.5]] y = x*w+b

In [0]:
#finding the index of the minimum and maximum
a = tf.constant([13,2,20,10,1,2,3]) 
print(sess.run(tf.argmin(a))) 
print(sess.run(tf.argmax(a)))

4
2


In [0]:
a = tf.constant( [[1,1,1], [2,2,2]] ) 
print("a:",sess.run(a)) 
print("Reduced Sum:",sess.run(tf.reduce_sum(a))) 
print(sess.run(tf.reduce_sum(a, 0))) # Column sum 
print(sess.run(tf.reduce_sum(a, 1))) # Row sum

a: [[1 1 1]
 [2 2 2]]
Reduced Sum: 9
[3 3 3]
[3 6]


In [0]:
#from -10 to 10, create a row that has 10 values equally spaced
#generates 10 numbers equally spaced between -10 to 10
a = tf.linspace(-10., 10., 10)
print(sess.run(a))


[-10.         -7.7777777  -5.5555553  -3.333333   -1.1111107   1.1111116
   3.333334    5.5555563   7.7777786  10.       ]


In [0]:
a = tf.linspace(-10., 10., 50)
print(sess.run(a))


[-10.          -9.591837    -9.183674    -8.77551     -8.367347
  -7.9591837   -7.55102     -7.142857    -6.7346935   -6.3265305
  -5.9183674   -5.510204    -5.102041    -4.693877    -4.285714
  -3.8775508   -3.4693875   -3.0612242   -2.653061    -2.2448976
  -1.8367344   -1.4285711   -1.0204079   -0.6122446   -0.2040813
   0.20408198   0.61224526   1.0204085    1.4285718    1.8367351
   2.2448983    2.6530616    3.061225     3.4693882    3.8775516
   4.2857146    4.693878     5.1020412    5.510205     5.918368
   6.3265314    6.7346945    7.1428576    7.551021     7.959184
   8.367348     8.775511     9.183674     9.591837    10.        ]


In [0]:
#during initialization of neural networks
#use a placeholder
a = tf.placeholder(tf.float32) 
b = tf.placeholder(tf.float32) 
sum = tf.add(a,b) 
print(sess.run(sum,feed_dict={a:3,b:4}))

In [0]:
#Variable
a = tf.Variable([.3], tf.float32) 
b = tf.Variable([-.1], tf.float32) 
x = tf.placeholder(tf.float32) 
y = a * x + b

In [0]:
#---------------------------------------------------------------------------------------

In [0]:
#-----------------------------------DATASETS & Data Split--------------------------------

In [0]:
# softmax activation function explanation:
# if the number of neurons in the output layer is more than 2, then you must use the softmax activation function
# each of the neurons represents one of the class
# # let us say we have 4 different images: dog, cat, bird and car
# that is why we put 4 neurons in our output layer
#one of the classes, let us say dog neuron replaces one of the neurons in the output layer

# softmax converts the raw number into a probability
# the way it does it is by taking each of the raw values given from the output and dividing it by the sum of total raw values given out by each of the neurons in the output layer
# and based on the probability, it states what image it is whether it is a dog image, or a car image for example

# if you don't use softmax, then you'll have to go through if loop to derive the result